### ISSUE TITLE
How can I run a script before the executable?

### ISSUE THREAD

**Issue by Faugus** [Open-Wine-Components/ULWGL#119]
I'm trying to run [this](https://github.com/gurrgur/er-patcher) script to unlock the framerate on Elden Ring.
It works if I run the game on Steam with `python er-patcher --rate 120 -- %command%` but when I try with UMU-Launcher outside Steam, it gives me a pop up with the message "File not found". What am I doing wrong?

```
[faugus@archlinux ~]$ UMU_LOG=debug WINEPREFIX=/home/faugus/.config/faugus-launcher/prefixes/elden-ring GAMEID=elden-ring umu-run /usr/bin/python "'/mnt/data/Games/Elden Ring/Game/er-patcher' --rate 120 -- '/mnt/data/Games/Elden Ring/Game/eldenring.exe'"
DEBUG [umu_run.main:528]:Arguments: ('/usr/bin/python', ["'/mnt/data/Games/Elden Ring/Game/er-patcher' --rate 120 -- '/mnt/data/Games/Elden Ring/Game/eldenring.exe'"])
DEBUG [umu_runtime.setup_umu:209]:Root: /usr/share/umu
DEBUG [umu_runtime.setup_umu:210]:Local: /home/faugus/.local/share/umu
DEBUG [umu_proton.get_umu_proton:59]:Sending request to api.github.com
DEBUG [umu_runtime._update_umu:241]:Existing install detected
DEBUG [umu_runtime._update_umu:267]:Runtime: sniper_platform_0.20240618.92328
steamrt3 is up to date
UMU-Proton is up to date
DEBUG [umu_run.setup_pfx:142]:Skipping link creation for prefix
DEBUG [umu_run.setup_pfx:143]:User steamuser directory exists: /home/faugus/.config/faugus-launcher/prefixes/elden-ring/drive_c/users/steamuser
DEBUG [umu_run.setup_pfx:144]:User home directory exists: /home/faugus/.config/faugus-launcher/prefixes/elden-ring/drive_c/users/faugus
INFO [umu_run.main:581]:WINEPREFIX=/mnt/data/backup-config/faugus-launcher/prefixes/elden-ring
INFO [umu_run.main:581]:GAMEID=elden-ring
INFO [umu_run.main:581]:PROTON_CRASH_REPORT_DIR=/tmp/umu_crashreports
INFO [umu_run.main:581]:PROTONPATH=/home/faugus/.local/share/Steam/compatibilitytools.d/UMU-Proton-9.0-beta16-2
INFO [umu_run.main:581]:STEAM_COMPAT_APP_ID=0
INFO [umu_run.main:581]:STEAM_COMPAT_TOOL_PATHS=/home/faugus/.local/share/Steam/compatibilitytools.d/UMU-Proton-9.0-beta16-2:/home/faugus/.local/share/umu
INFO [umu_run.main:581]:STEAM_COMPAT_LIBRARY_PATHS=
INFO [umu_run.main:581]:STEAM_COMPAT_MOUNTS=/home/faugus/.local/share/Steam/compatibilitytools.d/UMU-Proton-9.0-beta16-2:/home/faugus/.local/share/umu
INFO [umu_run.main:581]:STEAM_COMPAT_INSTALL_PATH=/usr/bin
INFO [umu_run.main:581]:STEAM_COMPAT_CLIENT_INSTALL_PATH=
INFO [umu_run.main:581]:STEAM_COMPAT_DATA_PATH=/mnt/data/backup-config/faugus-launcher/prefixes/elden-ring
INFO [umu_run.main:581]:STEAM_COMPAT_SHADER_PATH=/mnt/data/backup-config/faugus-launcher/prefixes/elden-ring/shadercache
INFO [umu_run.main:581]:FONTCONFIG_PATH=
INFO [umu_run.main:581]:EXE=/usr/bin/python3.12
INFO [umu_run.main:581]:SteamAppId=0
INFO [umu_run.main:581]:SteamGameId=0
INFO [umu_run.main:581]:STEAM_RUNTIME_LIBRARY_PATH=/usr/lib:/usr/bin:/usr/lib32
INFO [umu_run.main:581]:STORE=
INFO [umu_run.main:581]:PROTON_VERB=waitforexitandrun
INFO [umu_run.main:581]:UMU_ID=elden-ring
INFO [umu_run.main:581]:ULWGL_ID=elden-ring
INFO [umu_run.main:581]:UMU_ZENITY=
DEBUG [umu_run.main:596]:['/home/faugus/.local/share/umu/umu', '--verb', 'waitforexitandrun', '--', '/home/faugus/.local/share/Steam/compatibilitytools.d/UMU-Proton-9.0-beta16-2/proton', 'waitforexitandrun', '/usr/bin/python3.12', "'/mnt/data/Games/Elden Ring/Game/er-patcher' --rate 120 -- '/mnt/data/Games/Elden Ring/Game/eldenring.exe'"]
pressure-vessel-wrap[63449]: W: Not sharing path STEAM_COMPAT_INSTALL_PATH="/usr/bin" with container because "/usr" is reserved by the container framework
ProtonFixes[63525] INFO: Running protonfixes
ProtonFixes[63525] INFO: Running checks
ProtonFixes[63525] INFO: All checks successful
ProtonFixes[63525] INFO: Using global defaults for UNKNOWN (elden-ring)
ProtonFixes[63525] INFO: No global protonfix found for UNKNOWN (elden-ring)
Proton: /usr/bin/python3.12
Proton: Executable a unix path, launching with /unix option.
fsync: up and running.
Application could not be started, or no application associated with the specified file.
ShellExecuteEx failed: Success.

DEBUG [umu_run.run_command:479]:Child 63449 exited with wait status: 1

```

**Comment by R1kaB3rN** [comment]
The above is incorrect usage as all arguments following umu-run will be executed inside the container runtime. To execute outside the container, the commands need to precede umu-run. Here's a simple example to use umu-run with gamescope:

> GAMEID=0 gamescope -F fsr -- umu-run winecfg

To make this clear to CLI users though, we should probably document this by adding an example.

**Comment by R1kaB3rN** [comment]
Actually, the example I listed is one of the cases where it must precede umu-run. However, some binaries/scripts can be executed inside the container as long as the dependencies are in the runtime. The sniper platform currently uses Python 3.9 which meets the minimum requirements for that script, so they are covered. However, I think your usage is still wrong as you're referencing a path in /usr which is not supported in Pressure Vessel so please try:

```
UMU_LOG=debug WINEPREFIX=/home/faugus/.config/faugus-launcher/prefixes/elden-ring GAMEID=elden-ring umu-run /mnt/data/Games/Elden Ring/Game/er-patcher --rate 120 -- /mnt/data/Games/Elden Ring/Game/eldenring.exe
```

The er-patcher script includes a Python shebang, so you do not need to explicitly precede the script with the Python path.

**Comment by Faugus** [comment]
It worked for me using this comand:
```
WINEPREFIX=/home/faugus/.config/faugus-launcher/prefixes/elden-ring GAMEID=elden-ring /usr/bin/python '/mnt/data/Games/Elden Ring/Game/er-patcher' --rate 120 -- umu-run "/mnt/data/Games/Elden Ring/Game/eldenring.exe"
```
The command you suggested gives this error:
```
[faugus@archlinux Game]$ UMU_LOG=debug WINEPREFIX=/home/faugus/.config/faugus-launcher/prefixes/elden-ring GAMEID=elden-ring umu-run '/mnt/data/Games/Elden Ring/Game/er-patcher' --rate 120 -- '/mnt/data/Games/Elden Ring/Game/eldenring.exe'
DEBUG [umu_run.main:528]:Arguments: ('/mnt/data/Games/Elden Ring/Game/er-patcher', ['--rate', '120', '--', '/mnt/data/Games/Elden Ring/Game/eldenring.exe'])
DEBUG [umu_proton.get_umu_proton:59]:Sending request to api.github.com
DEBUG [umu_runtime.setup_umu:209]:Root: /usr/share/umu
DEBUG [umu_runtime.setup_umu:210]:Local: /home/faugus/.local/share/umu
DEBUG [umu_runtime._update_umu:241]:Existing install detected
DEBUG [umu_runtime._update_umu:267]:Runtime: sniper_platform_0.20240618.92328
steamrt3 is up to date
UMU-Proton is up to date
DEBUG [umu_run.setup_pfx:142]:Skipping link creation for prefix
DEBUG [umu_run.setup_pfx:143]:User steamuser directory exists: /home/faugus/.config/faugus-launcher/prefixes/elden-ring/drive_c/users/steamuser
DEBUG [umu_run.setup_pfx:144]:User home directory exists: /home/faugus/.config/faugus-launcher/prefixes/elden-ring/drive_c/users/faugus
INFO [umu_run.main:581]:WINEPREFIX=/mnt/data/backup-config/faugus-launcher/prefixes/elden-ring
INFO [umu_run.main:581]:GAMEID=elden-ring
INFO [umu_run.main:581]:PROTON_CRASH_REPORT_DIR=/tmp/umu_crashreports
INFO [umu_run.main:581]:PROTONPATH=/home/faugus/.local/share/Steam/compatibilitytools.d/UMU-Proton-9.0-beta16-2
INFO [umu_run.main:581]:STEAM_COMPAT_APP_ID=0
INFO [umu_run.main:581]:STEAM_COMPAT_TOOL_PATHS=/home/faugus/.local/share/Steam/compatibilitytools.d/UMU-Proton-9.0-beta16-2:/home/faugus/.local/share/umu
INFO [umu_run.main:581]:STEAM_COMPAT_LIBRARY_PATHS=/mnt/data
INFO [umu_run.main:581]:STEAM_COMPAT_MOUNTS=/home/faugus/.local/share/Steam/compatibilitytools.d/UMU-Proton-9.0-beta16-2:/home/faugus/.local/share/umu
INFO [umu_run.main:581]:STEAM_COMPAT_INSTALL_PATH=/mnt/data/Games/Elden Ring/Game
INFO [umu_run.main:581]:STEAM_COMPAT_CLIENT_INSTALL_PATH=
INFO [umu_run.main:581]:STEAM_COMPAT_DATA_PATH=/mnt/data/backup-config/faugus-launcher/prefixes/elden-ring
INFO [umu_run.main:581]:STEAM_COMPAT_SHADER_PATH=/mnt/data/backup-config/faugus-launcher/prefixes/elden-ring/shadercache
INFO [umu_run.main:581]:FONTCONFIG_PATH=
INFO [umu_run.main:581]:EXE=/mnt/data/Games/Elden Ring/Game/er-patcher
INFO [umu_run.main:581]:SteamAppId=0
INFO [umu_run.main:581]:SteamGameId=0
INFO [umu_run.main:581]:STEAM_RUNTIME_LIBRARY_PATH=/mnt/data/Games/Elden Ring/Game:/usr/lib32:/usr/lib
INFO [umu_run.main:581]:STORE=
INFO [umu_run.main:581]:PROTON_VERB=waitforexitandrun
INFO [umu_run.main:581]:UMU_ID=elden-ring
INFO [umu_run.main:581]:ULWGL_ID=elden-ring
INFO [umu_run.main:581]:UMU_ZENITY=
DEBUG [umu_run.main:596]:['/home/faugus/.local/share/umu/umu', '--verb', 'waitforexitandrun', '--', '/home/faugus/.local/share/Steam/compatibilitytools.d/UMU-Proton-9.0-beta16-2/proton', 'waitforexitandrun', '/mnt/data/Games/Elden Ring/Game/er-patcher', '--rate', '120', '--', '/mnt/data/Games/Elden Ring/Game/eldenring.exe']
ProtonFixes[94471] INFO: Running protonfixes
ProtonFixes[94471] INFO: Running checks
ProtonFixes[94471] INFO: All checks successful
ProtonFixes[94471] INFO: Using global defaults for UNKNOWN (elden-ring)
ProtonFixes[94471] INFO: No global protonfix found for UNKNOWN (elden-ring)
Proton: /mnt/data/Games/Elden Ring/Game/er-patcher
Proton: Executable a unix path, launching with /unix option.
fsync: up and running.
Traceback (most recent call last):
  File "/mnt/data/backup-config/faugus-launcher/prefixes/elden-ring/pfx/dosdevices/z:/mnt/data/Games/Elden Ring/Game/er-patcher", line 145, in <module>
    subprocess.run(steam_cmd, cwd=steam_cmd[-1].parent.absolute())
  File "/usr/lib/python3.9/subprocess.py", line 505, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.9/subprocess.py", line 1823, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
PermissionError: [Errno 13] Permission denied: PosixPath('/mnt/data/Games/Elden Ring/Game/er-patcher-tmp/eldenring.exe')
DEBUG [umu_run.run_command:479]:Child 94385 exited with wait status: 0

```

**Comment by Faugus** [comment]
Thank you very much @R1kaB3rN
