### ISSUE TITLE
Python-Error when starting umu from command-line

### ISSUE THREAD

**Issue by NBAB42Bq** [Open-Wine-Components/ULWGL#150]
Hi,

at first thanks for this nice piece of software.

Since the last umu-launcher-update (0.1.RC4.r224.8d81e87-2 / AUR / Arch Linux), I get always a Python-Error when starting umu-run from command-line. After the Error-Message umu runs in sequence twice. Reinstalled umu without success. Has anyone else this problem? (sry for my bad english)

 steamrt is up to date
Traceback (most recent call last):
  File "/bin/umu-run", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/lib/python3.12/site-packages/umu/__main__.py", line 9, in main
    return umu_run()
           ^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/umu/umu_run.py", line 778, in main
    return run_command(command)
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/umu/umu_run.py", line 641, in run_command
    gamescope_baselayer_sequence = get_gamescope_baselayer_order()
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/umu/umu_run.py", line 511, in get_gamescope_baselayer_order
    d = display.Display(":0")
        ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/Xlib/display.py", line 89, in __init__
    self.display = _BaseDisplay(display)
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/Xlib/display.py", line 71, in __init__
    protocol_display.Display.__init__(self, *args, **keys)
  File "/usr/lib/python3.12/site-packages/Xlib/protocol/display.py", line 166, in __init__
    raise error.DisplayConnectionError(self.display_name, r.reason)
Xlib.error.DisplayConnectionError: Can't connect to display ":0": b'Authorization required, but no authorization protocol specified\n'
steamrt is up to date
Traceback (most recent call last):
  File "/bin/umu-run", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/lib/python3.12/site-packages/umu/__main__.py", line 9, in main
    return umu_run()
           ^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/umu/umu_run.py", line 778, in main
    return run_command(command)
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/umu/umu_run.py", line 641, in run_command
    gamescope_baselayer_sequence = get_gamescope_baselayer_order()
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/umu/umu_run.py", line 511, in get_gamescope_baselayer_order
    d = display.Display(":0")
        ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/Xlib/display.py", line 89, in __init__
    self.display = _BaseDisplay(display)
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/Xlib/display.py", line 71, in __init__
    protocol_display.Display.__init__(self, *args, **keys)
  File "/usr/lib/python3.12/site-packages/Xlib/protocol/display.py", line 166, in __init__
    raise error.DisplayConnectionError(self.display_name, r.reason)
Xlib.error.DisplayConnectionError: Can't connect to display ":0": b'Authorization required, but no authorization protocol specified\n'
ProtonFixes[44488] INFO: Running protonfixes
ProtonFixes[44488] INFO: Running checks
ProtonFixes[44488] INFO: All checks successful
ProtonFixes[44542] INFO: Running protonfixes
ProtonFixes[44542] INFO: Running checks
ProtonFixes[44542] INFO: All checks successful
ProtonFixes[44488] INFO: Using global defaults for UNKNOWN (0)
ProtonFixes[44488] INFO: No global protonfix found for UNKNOWN (0)
Proton: <PATH/TO/GAME>.exe
Proton: Executable a unix path, launching with /unix option.
fsync: up and running.
ProtonFixes[44542] INFO: Using global defaults for UNKNOWN (0)
ProtonFixes[44542] INFO: No global protonfix found for UNKNOWN (0)
Bad system call (core dumped)
Proton: <PATH/TO/GAME>.exe
Proton: Executable a unix path, launching with /unix option.
fsync: up and running.

**Comment by R1kaB3rN** [comment]
Thanks for reporting this, and I’m glad to hear that you’re pleased with umu.

In the latest branch at https://github.com/Open-Wine-Components/umu-launcher/commit/295c7b8d3e42081860beb859ff49045a826506b3, umu is limiting the window setup functionality to gamescope sessions so this problem should be fixed. So, it’s up to @loathingKernel to update the PKGBUILD in the AUR.

In the future, a more proper solution will be explored to handle connecting to the correct displays for the general case. Same with Wayland.

**Comment by loathingKernel** [comment]
Thanks for the ping, updated.

**Comment by NBAB42Bq** [comment]
Thanks for your fast reply and the update! :)
