### ISSUE TITLE
Can't play without internet

### ISSUE THREAD

**Issue by mistermookiefun** [Open-Wine-Components/ULWGL#190]
Hey!
All in the title, why am I obliged to have an internet connection to play my offline games while travelling? :(

Code:
`Traceback (most recent call last):
  File "/usr/bin/umu-run", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/lib/python3.12/site-packages/umu/__main__.py", line 9, in main
    return umu_run()
           ^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/umu/umu_run.py", line 827, in main
    future.result()
  File "/usr/lib/python3.12/concurrent/futures/_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/usr/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/umu/umu_runtime.py", line 198, in setup_umu
    _update_umu(local, json, thread_pool)
  File "/usr/lib/python3.12/site-packages/umu/umu_runtime.py", line 312, in _update_umu
    client_session.request(
  File "/usr/lib/python3.12/http/client.py", line 1336, in request
    self._send_request(method, url, body, headers, encode_chunked)
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.12/http/client.py", line 1331, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.12/http/client.py", line 1091, in _send_output
    self.send(msg)
  File "/usr/lib/python3.12/http/client.py", line 1035, in send
    self.connect()
  File "/usr/lib/python3.12/http/client.py", line 1470, in connect
    super().connect()
  File "/usr/lib/python3.12/http/client.py", line 1001, in connect
    self.sock = self._create_connection(
                ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/socket.py", line 841, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/socket.py", line 976, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
socket.gaierror: [Errno -3] Temporary failure in name resolution
`

**Comment by R1kaB3rN** [comment]
Hey, thanks for the report.

A fix for this issue was merged in the latest main branch. Do you mind taking the time and rebuilding? You can do this easily by installing umu as a user. Please see the README on how to do that. 

However, if you're not able to build it right now, as a workaround, please set `UMU_RUNTIME_UPDATE=0.` And if you're still running into the issue, feel free to make reopen this issue and paste the traceback. But when you do, please be sure you are using the user install.

**Comment by R1kaB3rN** [comment]
>  All in the title, why am I obliged to have an internet connection to play my offline games while travelling? :(

I agree, it's unreasonable to require an internet connection for this program at all times. To clarify, the goal is to only require to have an internet connection for the initial setup -- after it installs all the runtime files.

Afterwards, an internet connection should not be required and umu-launcher should not crash or hang when launching games. If that ever happens, it needs to reported.

**Comment by mistermookiefun** [comment]
Hey!
Just updated the program to the latest AUR release (0.1.RC4.r280.4874190-1).
Here's what I get when launching 

`
Traceback (most recent call last):
  File "/usr/bin/umu-run", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/lib/python3.12/site-packages/umu/__main__.py", line 9, in main
    return umu_run()
           ^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/umu/umu_run.py", line 801, in main
    future.result()
  File "/usr/lib/python3.12/concurrent/futures/_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/usr/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/umu/umu_runtime.py", line 205, in setup_umu
    _update_umu(local, json, thread_pool, client_session)
  File "/usr/lib/python3.12/site-packages/umu/umu_runtime.py", line 325, in _update_umu
    client_session.request(
  File "/usr/lib/python3.12/http/client.py", line 1336, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.12/http/client.py", line 1382, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.12/http/client.py", line 1331, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.12/http/client.py", line 1091, in _send_output
    self.send(msg)
  File "/usr/lib/python3.12/http/client.py", line 1035, in send
    self.connect()
  File "/usr/lib/python3.12/http/client.py", line 1470, in connect
    super().connect()
  File "/usr/lib/python3.12/http/client.py", line 1001, in connect
    self.sock = self._create_connection(
                ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/socket.py", line 841, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/socket.py", line 976, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
socket.gaierror: [Errno -3] Temporary failure in name resolution
`

But it works with UMU_RUNTIME_UPDATE=0

**Comment by R1kaB3rN** [comment]
> Hey! Just updated the program to the latest AUR release (0.1.RC4.r280.4874190-1). Here's what I get when launching
> 
> `Traceback (most recent call last): File "/usr/bin/umu-run", line 8, in <module> sys.exit(main()) ^^^^^^ File "/usr/lib/python3.12/site-packages/umu/__main__.py", line 9, in main return umu_run() ^^^^^^^^^ File "/usr/lib/python3.12/site-packages/umu/umu_run.py", line 801, in main future.result() File "/usr/lib/python3.12/concurrent/futures/_base.py", line 449, in result return self.__get_result() ^^^^^^^^^^^^^^^^^^^ File "/usr/lib/python3.12/concurrent/futures/_base.py", line 401, in __get_result raise self._exception File "/usr/lib/python3.12/concurrent/futures/thread.py", line 58, in run result = self.fn(*self.args, **self.kwargs) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/lib/python3.12/site-packages/umu/umu_runtime.py", line 205, in setup_umu _update_umu(local, json, thread_pool, client_session) File "/usr/lib/python3.12/site-packages/umu/umu_runtime.py", line 325, in _update_umu client_session.request( File "/usr/lib/python3.12/http/client.py", line 1336, in request self._send_request(method, url, body, headers, encode_chunked) File "/usr/lib/python3.12/http/client.py", line 1382, in _send_request self.endheaders(body, encode_chunked=encode_chunked) File "/usr/lib/python3.12/http/client.py", line 1331, in endheaders self._send_output(message_body, encode_chunked=encode_chunked) File "/usr/lib/python3.12/http/client.py", line 1091, in _send_output self.send(msg) File "/usr/lib/python3.12/http/client.py", line 1035, in send self.connect() File "/usr/lib/python3.12/http/client.py", line 1470, in connect super().connect() File "/usr/lib/python3.12/http/client.py", line 1001, in connect self.sock = self._create_connection( ^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/lib/python3.12/socket.py", line 841, in create_connection for res in getaddrinfo(host, port, 0, SOCK_STREAM): ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/lib/python3.12/socket.py", line 976, in getaddrinfo for res in _socket.getaddrinfo(host, port, family, type, proto, flags): ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ socket.gaierror: [Errno -3] Temporary failure in name resolution`
> 
> But it works with UMU_RUNTIME_UPDATE=0

The AUR package is outdated and that pasted traceback supports it as the line numbers mismatches to the latest git.

cc @loathingKernel 

For now, until it's updated, uninstall that package and try again but when installing as a user. Once you do, the launcher will handle that exception and not crash. Please see the README for instructions on how to do that.

**Comment by mistermookiefun** [comment]
Hey!
Will do, thanks @R1kaB3rN <3
